//global class World
public class World{
    private String greeting = 'deepak';
    //public variable
    public String publicgreeting = 'my public greeting variable';
    
/*    public String morning = 'good morning';
    public String night = 'good night';*/
    
   /* public void printmorning(){
		System.debug(morning);
    }
    public void printnight(){
		System.debug(night);
    }
    
    public void printgreeting(){
        System.debug(greeting);
    }*/
    
    public void printMessage(String msg){
        System.debug(msg);
    }
    
    /*global void printgreeting(){
        System.debug(greeting);
    }*/

    
}